---

# Create a mount point for the EFS
runcmd:
  - [mkdir, -p, "${mount_point}"]
  - [chown, "${owner}:${group}", "${mount_point}"]

# Add an fstab entry for the EFS mount
mounts:
  # yamllint disable-line rule:line-length
  - ["${efs_id}:/", "${mount_point}", efs, "_netdev,iam,nofail,tls,accesspoint=${efs_ap_id}", "0", "0"]